export const PAGE_CHANGED = 'PAGE_CHANGED';

export const TAG_ADD_TO_CART = 'TAG_ADD_TO_CART';
export const TAG_REMOVE_FROM_CART = 'TAG_REMOVE_FROM_CART';

export const TAG_VIRTUAL_PAGE_VIEW = 'TAG_VIRTUAL_PAGE_VIEW';

export const TAG_PRODUCT_IMPRESSIONS = 'TAG_PRODUCT_IMPRESSIONS';
export const TAG_PRODUCT_CLICKS = 'TAG_PRODUCT_CLICKS';
