export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_DUPLICATE = 'CREATE_TOPIC_DUPLICATE';
export const GET_TOPICS = 'GET_TOPICS';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';
export const TYPING = 'TYPING';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const SET_PRICELISTZONEID = 'SET_PRICELISTZONEID';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
export const SET_USERNAME = 'SET_USERNAME';

export const CHECK_DELIVERABLE = 'CHECK_DELIVERABLE';
export const SET_PROVINCE_DATA = 'SET_PROVINCE_DATA';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const UPDATE_PRODUCT_ITEM_COUNT = 'UPDATE_PRODUCT_ITEM_COUNT';
export const UPDATE_FAVORITE_LIST = 'UPDATE_FAVORITE_LIST';
export const UPDATE_FAVORITE_LIST_REMOVE = 'UPDATE_FAVORITE_LIST_REMOVE';
export const HIDE_DELIVERY_SLOT = 'HIDE_DELIVERY_SLOT';
export const SHOW_DELIVERY_SLOT = 'SHOW_DELIVERY_SLOT';
export const GET_ALL_ITEMS_IN_WISHLIST_SUCCESS = 'GET_ALL_ITEMS_IN_WISHLIST_SUCCESS';
export const GET_ALL_ITEMS_IN_WISHLIST_FAILURE = 'GET_ALL_ITEMS_IN_WISHLIST_FAILURE';

export const SHOW_MOBILE_VIEWPORT = 'SHOW_MOBILE_VIEWPORT';
// export const HIDE_MOBILE_VIEWPORT = 'HIDE_MOBILE_VIEWPORT';
export const SHOW_DESKTOP_VIEWPORT = 'SHOW_DESKTOP_VIEWPORT';

export const COLLAPSE_ALL = 'COLLAPSE_ALL';
export const SET_ACTIVE = 'SET_ACTIVE';
export const DESELECT_HEADER_OPTION = 'DESELECT_HEADER_OPTION';
export const SELECT_HEADER_OPTION = 'SELECT_HEADER_OPTION';

export const SET_USER_ORDERS = 'SET_USER_ORDERS';
export const RESET_ORDER_DETAILS = 'RESET_ORDER_DETAILS';
export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS';

export const FETCH_CURRENT_USER_ADDRESSES_SUCCESS = 'FETCH_CURRENT_USER_ADDRESSES_SUCCESS';
export const FETCH_CURRENT_USER_ADDRESSES_FAILURE = 'FETCH_CURRENT_USER_ADDRESSES_FAILURE';

// export const SET_PREVIOUS_LOCATION = 'SET_PREVIOUS_LOCATION';
export const SET_PREVIOUS_LOCATION = 'SET_PREVIOUS_LOCATION';

export const SET_CHECKOUT_ACTIVE_STEP = 'SET_CHECKOUT_ACTIVE_STEP';
export const UPDATE_SHIPPING_INFO = 'UPDATE_SHIPPING_INFO';
export const UPDATE_SHIPPING_INSTRUCTION = 'UPDATE_SHIPPING_INSTRUCTION';
export const FETCH_PAY_AND_CHECKOUT_FORM = 'FETCH_PAY_AND_CHECKOUT_FORM';
export const ORDER_COMPLETED = 'ORDER_COMPLETED';

export const SET_DELIVERY_SLOT_SESSION = 'SET_DELIVERY_SLOT_SESSION';

export const SET_SEO_INFORMATION = 'SET_SEO_INFORMATION';
export const RESET_SEO_INFORMATION = 'RESET_SEO_INFORMATION';
